import { useTranslation } from 'react-i18next';
import { View } from 'react-native';

import { Card, Screen, Text, colors, space } from '@/ui';

import licenses from './licenses.json';

type LicenseEntry = {
  name: string;
  version: string;
  license: string;
  publisher?: string;
};

/** Generated by `npm run licenses` — never edited by hand. */
export function LicensesScreen(): React.JSX.Element {
  const { t } = useTranslation();
  const entries = licenses as LicenseEntry[];

  return (
    <Screen>
      <Text variant="h2" accessibilityRole="header">
        {t('about.licensesTitle')}
      </Text>
      <View style={{ gap: space.md }}>
        {entries.map((entry) => (
          <Card
            key={`${entry.name}@${entry.version}`}
            radiusToken="factorCard"
            style={{ paddingVertical: space.xl, paddingHorizontal: space.xxl }}
          >
            <Text variant="rowTitle">{entry.name}</Text>
            <Text variant="caption" color={colors.textAlpha[55]} style={{ marginTop: space.xxs }}>
              {`${entry.version} · ${entry.license}${entry.publisher === undefined ? '' : ` · ${entry.publisher}`}`}
            </Text>
          </Card>
        ))}
      </View>
    </Screen>
  );
}
